"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e&105t+s=yel6^so3p22ez=4*5qzvl*njqhw7x)5frw1&9-vec'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'djello',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'appauth',
    'sample_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'appauth.AppUser'


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Djello settings
DJELLO = {
    'header_logo': 'djello/images/logo.png',
    'welcome_logo': 'djello/images/logo.png',
    'icons': [],
    'header_links': [('/api/', 'fa-rss'), ('/flower/', 'fa-tasks')],
    'menu': {
        'appauth': {
            'icon': 'fa-users',
            'model_icons': {
                'AppUser': 'fa-user',
                'Role': 'fa-briefcase'}},
        'sample_app': {
            'icon': 'fa-tasks',
            'model_icons': {
                'Post': 'fa-bullhorn'}},
        'django_celery_beat': {
            'icon': 'fa-calendar', 'model_icons': {
                'CrontabSchedule': 'fa-calendar-o',
                'IntervalSchedule': 'fa-clock-o',
                'PeriodicTask': 'fa-refresh',
                'SolarSchedule': 'fa-sun-o'}},
        'simple_django_logger': {
            'icon': 'fa-files-o',
            'model_icons': {
                'EventLog': 'fa-bolt',
                'Log': 'fa-file-text',
                'RequestLog': 'fa-exchange'}}},
    'dashboard': [
        [
            {
                'widget': 'stat-widget',
                'id': 'anomaliesDetected',
                'icon': 'fa-umbrella',
                'color': 'flat-color-1',
                'size': '3',
                'data_url': 'sample_app_api:anomalies_detected'
            }, {
                'widget': 'stat-widget',
                'id': 'accountsScanned',
                'icon': 'fa-group',
                'color': 'flat-color-2',
                'size': '3',
                'data_url': 'sample_app_api:accounts_scanned'
            }, {
                'widget': 'stat-widget',
                'id': 'logsProcessed',
                'icon': 'fa-gears',
                'color': 'flat-color-3',
                'size': '3',
                'data_url': 'sample_app_api:logs_processed'
            }, {
                'widget': 'stat-widget',
                'id': 'peanutsEaten',
                'icon': 'fa-lemon-o',
                'color': 'flat-color-4',
                'size': '3',
                'data_url': 'sample_app_api:peanuts_eaten'
            }
        ],
        [
            {
                'widget': 'graph-widget',
                'id': '',
                'size': '12',
                'data_url': '',
            }
        ],
        [
            {'widget': 'recent-actions-widget', 'id': '', 'size': '6'},
            {'widget': 'chat-widget', 'id': '', 'size': '6'}
        ],
        [
            {
                'widget': 'chartjs-widget',
                'id': 'salesChart',
                'size': '6',
                'data_url': 'sample_app_api:yearly_sales',
            }, {
                'widget': 'chartjs-widget',
                'id': 'barChart',
                'size': '6',
                'data_url': 'sample_app_api:bar_chart',
            }
        ],
        [
            {
                'widget': 'chartjs-widget',
                'id': 'radarChart',
                'size': '6',
                'data_url': 'sample_app_api:radar_chart',
            }, {
                'widget': 'chartjs-widget',
                'id': 'doughnutChart',
                'size': '6',
                'data_url': 'sample_app_api:doughnut_chart',
            }
        ]
    ],
}
